### ISSUE TITLE
Nested `asset.json` configs

### ISSUE THREAD

**Issue by thejdmego** [ov-sa/Assetify-Library#15]
Goal is to allow users to make separate config files for different data.  

For example:  
*before:*
```
{
    "streamRange": 170,
    "enableLODs": false,
    "assetTransparency": false,
    "sceneDimension": 0,
    "sceneInterior": 0,
    "sceneOffset": { "x": 0, "y": 0, "z": 0 },

    "spawn": [
        {
            "position": { "x": 0, "y": 0, "z": 0 },
            "rotation": { "x": 0, "y": 0, "z": 0 }
        }
    ]
}
```
*after:*  
```
{
    "streamRange": 170,
    "enableLODs": false,
    "assetTransparency": false,
    "sceneDimension": 0,
    "sceneInterior": 0,
    "sceneOffset": { "x": 0, "y": 0, "z": 0 },

    "spawn": "@spawn.json"
}
```

**Comment by Aviril** [comment]
> Goal is to allow users to make separate config files for different data.
> 
> For example: _before:_
> 
> ```
> {
>     "streamRange": 170,
>     "enableLODs": false,
>     "assetTransparency": false,
>     "sceneDimension": 0,
>     "sceneInterior": 0,
>     "sceneOffset": { "x": 0, "y": 0, "z": 0 },
> 
>     "spawn": [
>         {
>             "position": { "x": 0, "y": 0, "z": 0 },
>             "rotation": { "x": 0, "y": 0, "z": 0 }
>         }
>     ]
> }
> ```
> 
> _after:_
> 
> ```
> {
>     "streamRange": 170,
>     "enableLODs": false,
>     "assetTransparency": false,
>     "sceneDimension": 0,
>     "sceneInterior": 0,
>     "sceneOffset": { "x": 0, "y": 0, "z": 0 },
> 
>     "spawn": "@spawn.json"
> }
> ```

Implemented. Kindly refer: https://github.com/ov-sa/Assetify-Library/releases/tag/v.4.3.0
