### ISSUE TITLE
`onElementDataChange` analog events

### ISSUE THREAD

**Issue by thejdmego** [ov-sa/Assetify-Library#16]
[Syncer](https://github.com/ov-sa/Assetify-Library/wiki/Feature:-Syncer) module lacks this events to track global/entity data changing both for client and server.

**Comment by OvileAmriam** [comment]
Added Global & Entity data tracker networks as indicated below:
```lua
--Tracks global data changes
network:fetch("Assetify:onGlobalDataChange", true):on(function(data, oldValue, newValue)

end)

--Tracks entity data changes
network:fetch("Assetify:onEntityDataChange", true):on(function(element, data, oldValue, newValue)

end)
```
Source: https://github.com/ov-sa/Assetify-Library/releases/tag/v.3.1.4
