### ISSUE TITLE
Review Buffer Cache

### ISSUE THREAD

**Issue by OvileAmriam** [ov-sa/Assetify-Library#17]
@Aviril needs some fixes and review to confirm. For instance this is most likely wrong: https://github.com/ov-sa/Assetify-Library/blob/main/%5BLibrary%5D/assetify_library/utilities/dummy.lua#L134

**Comment by Aviril** [comment]
> @Aviril needs some fixes and review to confirm. For instance this is most likely wrong: https://github.com/ov-sa/Assetify-Library/blob/main/%5BLibrary%5D/assetify_library/utilities/dummy.lua#L134

Reviewed, had wrong indexing issue; Fixed it for the latter versions. Other classes are fine.
