### ISSUE TITLE
Add a helper function to avoid recoding buildShader twice 

### ISSUE THREAD

**Issue by OvileAmriam** [ov-sa/Assetify-Library#20]
Make a helper function so asset and shader classes can share datas without rewriting the entire same thing which would be nuisance to maintain.

**Comment by OvileAmriam** [comment]
https://github.com/ov-sa/Assetify-Library/blob/main/%5BLibrary%5D/assetify_library/utilities/engine/asset.lua#L243

**Comment by Aviril** [comment]
Kindly [refer](https://github.com/ov-sa/vRPZ-Framework/commit/145ee86ce9b0d88e16d666f5573b38a9bf7898fa). Will merge once tested and reviewed. Further more reference paths for `dff/`, `txd/`, `col/` could perhaps be specified.

**Comment by OvileAmriam** [comment]
> Kindly [refer](https://github.com/ov-sa/vRPZ-Framework/commit/145ee86ce9b0d88e16d666f5573b38a9bf7898fa). Will merge once tested and reviewed. Further more reference paths for `dff/`, `txd/`, `col/` could perhaps be specified.

Tested, everything works fine. Looking forward to getting this merged!

**Comment by Aviril** [comment]
Merged in the release: https://github.com/ov-sa/Assetify-Library/releases/tag/v.6.1.0
