### ISSUE TITLE
Scene Dimension (-1) Bug

### ISSUE THREAD

**Issue by OvileAmriam** [ov-sa/Assetify-Library#21]
Scenes having set `sceneDimension` as `-1` doesn't appear when changing dimensions now for some reason.

**Comment by Aviril** [comment]
Review: https://github.com/ov-sa/vRPZ-Framework/commit/33e63facdfe370052c467b43d31d068d97e23c18

**Comment by OvileAmriam** [comment]
Nope, issue still persists

**Comment by Aviril** [comment]
Patched & Merged: https://github.com/ov-sa/Assetify-Library/releases/tag/v.6.1.1
