### ISSUE TITLE
Models not sync to new players

### ISSUE THREAD

**Issue by thejdmego** [ov-sa/Assetify-Library#30]
Asset model not applied to an element from player perspective who just joined the server (but element was created before player joined with `createDummy`).

It is appearing on vehicles and was tested by reconnecting after vehicle was created.
Vehicle is spawned, player can enter it, but model is `assetBase` and alpha is 0.

**Comment by Aviril** [comment]
> Asset model not applied to an element from player perspective who just joined the server (but element was created before player joined with `createDummy`).
> 
> It is appearing on vehicles and was tested by reconnecting after vehicle was created. Vehicle is spawned, player can enter it, but model is `assetBase` and alpha is 0.

Patched & merged w/ release: https://github.com/ov-sa/Assetify-Library/releases/tag/v.6.6.9
