### ISSUE TITLE
IDE compatibility (Flags, object definitions)

### ISSUE THREAD

**Issue by RaphaelPapini** [ov-sa/Assetify-Library#7]
### IDE Compatibility
Purpose: Bring the native GTA SA object definitions (IDE) to Assetify. IDE files can store information including distance, dff, id and flags (special attributions) to map models (dff's).

The following list includes a list of native GTA SA objects with their properties listed in the game files located in: sa/data/maps
Useful links: https://gtamods.com/wiki/Item_Definition
https://gta.fandom.com/wiki/IDE

(Note: The list isn't complete because I couldn't find some of the flags, but some of them are not really useful in this case).

- IS_ROAD - This model is a road.
17630, Lae2_roads26, lae2roads, 150, 1
- DRAW_LAST - Model is transparent. Render this object after all opaque objects, allowing transparencies of other objects to be visible through this object.
969, Electricgate, electricgate, 101, 4 
- ADDITIVE - Render with additive blending. Previous flag will be enabled automatically.	
4715, LTSLAsky1_LAn2, nightlights1_lan2, 600, 140, 20, 6
- NO_ZBUFFER_WRITE - Disable writing to z-buffer when rendering this model, allowing transparencies of other objects, shadows, and lights to be visible through this object.
?
- DONT_RECEIVE_SHADOWS - 	Do not draw shadows on this object.
1580, drug_red, dyn_drugs, 40, 128
- IS_GLASS_TYPE_1 - Breakable glass type 1 (additional parameters defined inside the object.dat file, otherwise there is no effect)	
?
- IS_GLASS_TYPE_2	 - Breakable glass type 2: object first cracks on a strong collision, then it breaks (does also require object.dat registration).	
?
- IS_GARAGE_DOOR	- Indicates an object as an garage door (for more information see GRGE – requires object.dat registration).	
17951, cjgaragedoor, contachou1_lae2, 100, 2048
- IS_DAMAGABLE - Model with ok/dam states.	
1188, fbmp_lr_sv2, savanna, 100, 4096
- IS_TREE - Trees and some plants. These objects move on wind.	
811, genVEG_bush15, gta_proc_grasslanda, 59, 8324
- IS_PALM	- Palms. These objects move on wind.
620, veg_palm04, gta_tree_palm, 150, 2146436
- DOES_NOT_COLLIDE_WITH_FLYER - Does not collide with flyer (plane or heli).
1226, lamppost3, dynsigns, 62, 32896
- IS_TAG - This model is a tag. Object will switch from mesh 2 to mesh 1 after getting sprayed by the player.	
1490, tag_01, tags2_LAlae, 100, 1048580
- DISABLE_BACKFACE_CULLING - ?
- IS_BREAKABLE_STATUE	 - Object with this model can't be used as cover, i.e. peds won't try to cover behind this object.	
?

**Comment by Aviril** [comment]
@RaphaelPapini Paste a example file for IDE so i can make script

**Comment by Fernando-A-Rocha** [comment]
> @RaphaelPapini Paste a example file for IDE so i can make script

You can search .ide in your GTA:SA Install directory to find many files.

Example: [countryW.ide](https://pastebin.com/UX0JUpPw)

**Comment by OvileAmriam** [comment]
> > @RaphaelPapini Paste a example file for IDE so i can make script
> 
> You can search .ide in your GTA:SA Install directory to find many files.
> 
> Example: [countryW.ide](https://pastebin.com/UX0JUpPw)

Yep, although in this case its useless for us to implement IDE support since you can just categorize your props into multiple scenes and globally assign to each asset its own `assetBase` model based on which it should be cloned to inherit properties. Fairly easier than IDE generation, modification, development. Also because we planned to implement streaming distance per asset packs

For example:
scene/terrain/asset.json : streamingDistance 500
scene/trees/asset.json : streamingDistance 10
scene/trees/streetlights.json : streamingDistance 2

Doing this via IDE requires you to reiterate through 3DS Max everytime you want to modify, that doesn't means it can't be implemented but regarding flexibility its better with personally categorized Asset Packs

**Comment by OvileAmriam** [comment]
Graphify will no longer be needed as dependency soon due to being bulky and performance reasons. Assetify should be functioning standalone in the next coming versions. Custom Asset clumping support has already been implemented & merged.

**Comment by OvileAmriam** [comment]
**Merged & Released:** https://github.com/ov-sa/Assetify-Library/releases/tag/v.1.0.7
