### ISSUE TITLE
Shared assetify.getAsset()

### ISSUE THREAD

**Issue by thejdmego** [ov-sa/Assetify-Library#9]
Make assetify.getAsset() function shared to get info about asset, check if asset exists, etc. on the server side.
It is useful for addon vehicle spawning (which needs to be used serverside) to check whether vehicle asset with provided name exist or not.

**Comment by OvileAmriam** [comment]
> Make assetify.getAsset() function shared to get info about asset, check if asset exists, etc. on the server side. It is useful for addon vehicle spawning (which needs to be used serverside) to check whether vehicle asset with provided name exist or not.

True @Aviril

**Comment by Aviril** [comment]
> Make assetify.getAsset() function shared to get info about asset, check if asset exists, etc. on the server side. It is useful for addon vehicle spawning (which needs to be used serverside) to check whether vehicle asset with provided name exist or not.



> > Make assetify.getAsset() function shared to get info about asset, check if asset exists, etc. on the server side. It is useful for addon vehicle spawning (which needs to be used serverside) to check whether vehicle asset with provided name exist or not.
> 
> True @Aviril

**Patched:** https://github.com/ov-sa/Assetify-Library/releases/tag/v.2.0.8
